import js from "@eslint/js";
import globals from "globals";

export default [
  js.configs.all,
  {
    files: ["scripts/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...globals.node,
        ...globals.es2024,
      },
    },
    rules: {
      "no-console": "warn",
      "no-unused-vars": "warn",
      "no-undef": "error",
      "no-var": "error",
      "prefer-const": "warn",
      "eqeqeq": "error",
      "curly": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-proto": "error",
      "no-extend-native": "error",
      "no-alert": "error",
      "no-caller": "error",
      "no-labels": "error",
      "no-lone-blocks": "error",
      "no-loop-func": "error",
      "no-multi-str": "error",
      "no-new-wrappers": "error",
      "no-octal-escape": "error",
      "no-return-assign": "error",
      "no-script-url": "error",
      "no-self-compare": "error",
      "no-sequences": "error",
      "no-throw-literal": "error",
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "no-useless-return": "error",
      "no-void": "error",
      "no-with": "error",
      "prefer-promise-reject-errors": "error",
      "radix": "error",
      "require-await": "warn",
      "no-shadow": "warn",
      "no-use-before-define": "warn",
      "no-duplicate-imports": "error",
      "no-useless-computed-key": "error",
      "no-useless-rename": "error",
      "prefer-arrow-callback": "warn",
      "prefer-destructuring": "warn",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "warn",
      "symbol-description": "error",
      "no-magic-numbers": ["warn", { "ignore": [0, 1, -1], "ignoreArrayIndexes": true }],
      "complexity": ["warn", 20],
      "max-depth": ["warn", 4],
      "max-nested-callbacks": ["warn", 4],
      "max-params": ["warn", 5],
    },
  },
  {
    ignores: ["node_modules/**", "**/wwwroot/**", "**/bin/**", "**/obj/**"],
  },
];
