export default {
  extends: ["stylelint-config-standard-scss"],
  rules: {
    "color-no-invalid-hex": true,
    "font-family-no-duplicate-names": true,
    "font-family-no-missing-generic-family-keyword": true,
    "named-grid-areas-no-invalid": true,
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-no-unknown": true,
    "string-no-newline": true,
    "unit-no-unknown": true,
    "property-no-unknown": true,
    "keyframe-declaration-no-important": true,
    "declaration-block-no-duplicate-custom-properties": true,
    "declaration-block-no-duplicate-properties": [true, { "ignore": ["consecutive-duplicates-with-different-syntaxes"] }],
    "declaration-block-no-shorthand-property-overrides": true,
    "block-no-empty": true,
    "selector-pseudo-class-no-unknown": [true, { "ignorePseudoClasses": ["deep", "global"] }],
    "selector-pseudo-element-no-unknown": true,
    "selector-type-no-unknown": [true, { "ignoreTypes": ["app", "/^blazor-/"] }],
    "media-feature-name-no-unknown": true,
    "at-rule-no-unknown": null,
    "no-descending-specificity": true,
    "no-duplicate-at-import-rules": true,
    "no-duplicate-selectors": true,
    "no-empty-source": true,
    "no-invalid-double-slash-comments": true,
    "no-invalid-position-at-import-rule": true,
    "alpha-value-notation": "percentage",
    "hue-degree-notation": "angle",
    "color-function-notation": "modern",
    "color-named": "never",
    "color-no-hex": null,
    "length-zero-no-unit": true,
    "font-weight-notation": "numeric",
    "function-url-no-scheme-relative": true,
    "number-max-precision": 4,
    "shorthand-property-no-redundant-values": true,
    "value-no-vendor-prefix": true,
    "property-no-vendor-prefix": true,
    "declaration-no-important": true,
    "declaration-block-single-line-max-declarations": 1,
    "selector-max-attribute": 2,
    "selector-max-class": 4,
    "selector-max-combinators": 4,
    "selector-max-compound-selectors": 4,
    "selector-max-id": 1,
    "selector-max-pseudo-class": 3,
    "selector-max-specificity": "1,4,4",
    "selector-max-type": 3,
    "selector-max-universal": 1,
    "selector-no-qualifying-type": [true, { "ignore": ["attribute", "class"] }],
    "selector-no-vendor-prefix": true,
    "media-feature-name-no-vendor-prefix": true,
    "at-rule-no-vendor-prefix": true,
    "no-unknown-animations": true,
    "value-keyword-case": "lower",
    "function-name-case": "lower",
    "selector-type-case": "lower",
    "rule-empty-line-before": ["always-multi-line", { "except": ["first-nested"], "ignore": ["after-comment"] }],
    "at-rule-empty-line-before": ["always", { "except": ["blockless-after-same-name-blockless", "first-nested"], "ignore": ["after-comment"] }],
    "comment-empty-line-before": ["always", { "except": ["first-nested"], "ignore": ["stylelint-commands"] }],
    "comment-whitespace-inside": "always",
    "max-nesting-depth": [4, { "ignoreAtRules": ["media", "supports", "include"] }],
    "scss/at-rule-no-unknown": true,
    "scss/comment-no-empty": true,
    "scss/declaration-nested-properties-no-divided-groups": true,
    "scss/dollar-variable-no-missing-interpolation": true,
    "scss/function-quote-no-quoted-strings-inside": true,
    "scss/function-unquote-no-unquoted-strings-inside": true,
    "scss/no-duplicate-dollar-variables": [true, { "ignoreInside": ["at-rule", "nested-at-rule"] }],
    "scss/no-duplicate-mixins": true,
    "scss/no-global-function-names": true,
    "scss/selector-no-redundant-nesting-selector": true,
    "scss/at-extend-no-missing-placeholder": true,
    "scss/at-if-no-null": true,
    "scss/at-mixin-argumentless-call-parentheses": "always",
    "scss/dollar-variable-colon-space-after": "always-single-line",
    "scss/dollar-variable-colon-space-before": "never",
    "scss/dollar-variable-empty-line-before": ["always", { "except": ["after-dollar-variable", "first-nested"], "ignore": ["after-comment"] }],
    "scss/double-slash-comment-empty-line-before": ["always", { "except": ["first-nested"], "ignore": ["between-comments", "stylelint-commands"] }],
    "scss/double-slash-comment-whitespace-inside": "always",
    "scss/operator-no-newline-after": true,
    "scss/operator-no-newline-before": true,
    "scss/operator-no-unspaced": true,
  },
  overrides: [
    {
      files: ["**/*.razor.scss"],
      rules: {},
    },
  ],
  ignoreFiles: [
    "**/*.css",
    "**/node_modules/**",
    "**/wwwroot/**",
    "**/bin/**",
    "**/obj/**",
  ],
};
