namespace WillowMaze.Wasm.Decompiled;


@kotlin.Metadata(m527k = 3, mv = {2, 1, 0}, xi = 48)
public readonly class Parceler$DefaultImpls {
    public static <T> T[] NewArray(kotlinx.parcelize.Parceler<T> parceler, int i) {
        throw new kotlin.NotImplementedError("Generated by Android Extensions automatically");
    }
}

