namespace WillowMaze.Wasm.Decompiled;

public class R_layout
{
    public static int Abc_action_bar_title_item;
    public static int Abc_action_bar_up_container;
    public static int Abc_action_menu_item_layout;
    public static int Abc_action_menu_layout;
    public static int Abc_action_mode_bar;
    public static int Abc_action_mode_close_item_material;
    public static int Abc_activity_chooser_view;
    public static int Abc_activity_chooser_view_list_item;
    public static int Abc_alert_dialog_button_bar_material;
    public static int Abc_alert_dialog_material;
    public static int Abc_alert_dialog_title_material;
    public static int Abc_dialog_title_material;
    public static int Abc_expanded_menu_layout;
    public static int Abc_list_menu_item_checkbox;
    public static int Abc_list_menu_item_icon;
    public static int Abc_list_menu_item_layout;
    public static int Abc_list_menu_item_radio;
    public static int Abc_popup_menu_header_item_layout;
    public static int Abc_popup_menu_item_layout;
    public static int Abc_screen_content_include;
    public static int Abc_screen_simple;
    public static int Abc_screen_simple_overlay_action_mode;
    public static int Abc_screen_toolbar;
    public static int Abc_search_dropdown_item_icons_2line;
    public static int Abc_search_view;
    public static int Abc_select_dialog_material;
    public static int Abc_tooltip;
    public static int Design_bottom_navigation_item;
    public static int Design_bottom_sheet_dialog;
    public static int Design_layout_snackbar;
    public static int Design_layout_snackbar_include;
    public static int Design_layout_tab_icon;
    public static int Design_layout_tab_text;
    public static int Design_menu_item_action_area;
    public static int Design_navigation_item;
    public static int Design_navigation_item_header;
    public static int Design_navigation_item_separator;
    public static int Design_navigation_item_subheader;
    public static int Design_navigation_menu;
    public static int Design_navigation_menu_item;
    public static int Notification_action;
    public static int Notification_action_tombstone;
    public static int Notification_media_action;
    public static int Notification_media_cancel_action;
    public static int Notification_template_big_media;
    public static int Notification_template_big_media_custom;
    public static int Notification_template_big_media_narrow;
    public static int Notification_template_big_media_narrow_custom;
    public static int Notification_template_custom_big;
    public static int Notification_template_icon_group;
    public static int Notification_template_lines_media;
    public static int Notification_template_media;
    public static int Notification_template_media_custom;
    public static int Notification_template_part_chronometer;
    public static int Notification_template_part_time;
    public static int Select_dialog_item_material;
    public static int Select_dialog_multichoice_material;
    public static int Select_dialog_singlechoice_material;
    public static int Support_simple_spinner_dropdown_item;

}
