namespace PrTask.Domain.Constants;
public static class DiditConstants
{
    public const string BaseUrl = "https://verification.didit.me";
    public const string CreateSessionPath = "/v3/session/";
    public const string RetrieveSessionPath = "/v3/session/{0}/decision/";
    public const string UpdateStatusPath = "/v3/session/{0}/update-status/";
    public const string ListSessionsPath = "/v3/session/";
    public const string DeleteSessionPath = "/v3/session/{0}/delete/";
    public const string ApiKeyHeader = "x-api-key";
    public const string HttpClientName = "DiditKyc";
    public const string ConfigApiKey = "Didit:ApiKey";
    public const string ConfigWorkflowId = "Didit:WorkflowId";
    public const string StatusNotStarted = "Not Started";
    public const string StatusApproved = "Approved";
    public const string StatusDeclined = "Declined";
    public const string StatusInProgress = "In Progress";
    public const string StatusInReview = "In Review";
    public const string StatusResubmitted = "Resubmitted";
    public const string StatusExpired = "Expired";
    public const string FeatureIdVerification = "ID_VERIFICATION";
    public const string FeatureLiveness = "LIVENESS";
    public const string FeatureFaceMatch = "FACE_MATCH";
    public const string FeatureAml = "AML";
    public const string FeatureNfc = "NFC";
    public const string PropertySessionId = "session_id";
    public const string PropertyUrl = "url";
    public const string PropertyStatus = "status";
    public const string PropertySessionToken = "session_token";
    public const string PropertyNewStatus = "new_status";
    public const string PropertyWorkflowId = "workflow_id";
    public const string PropertyVendorData = "vendor_data";
    public const string PropertyCallback = "callback";
    public const string PropertyCallbackMethod = "callback_method";
    public const string PropertySessionNumber = "session_number";
    public const string PropertyMetadata = "metadata";
    public const string PropertyLanguage = "language";
    public const string ContentTypeJson = "application/json";
    public const string PropertyFullName = "full_name";
    public const string PropertyComment = "comment";
    public const string QueryVendorDataFormat = "vendor_data={0}";
    public const string QueryStatusFormat = "status={0}";
    public const string QueryPathFormat = "{0}?{1}";
    public const string QueryKeyCallback = "callback";
    public const string QueryKeyVendorData = "vendor_data";
    public const string QueryKeyStatus = "status";
    public const string ErrorCreateSession = "Failed to create KYC session";
    public const string JsonSessionId = "sessionId";
    public const string JsonVerificationUrl = "verificationUrl";
    public const string JsonStatus = "status";
    public const string JsonFullName = "fullName";
    public const string QuerySeparator = "?";
    public const string WorkflowsPath = "/v3/workflows/";
    public const string WorkflowByIdPath = "/v3/workflows/{0}/";
    public const string PropertyWorkflowType = "workflow_type";
    public const string PropertyWorkflowLabel = "workflow_label";
    public const string PropertyUuid = "uuid";
    public const string WorkflowTypeKyc = "kyc";
    public const string DefaultWorkflowId = "be2f5870-262d-4e34-ac7d-b2e3070ce9a7";
    public const string ProviderName = "Didit";
    public const string PropertyContactDetails = "contact_details";
    public const string PropertyExpectedDetails = "expected_details";
    public const string PropertyDocumentType = "document_type";
    public const string PropertyDecisionTime = "decision_time";
    public const string PropertyEmail = "email";
    public const string PropertyPhone = "phone";
    public const string PropertyFirstName = "first_name";
    public const string PropertyLastName = "last_name";
    public const string PropertyDateOfBirth = "date_of_birth";
    public const string PropertyNationality = "nationality";
    public const string LogCreateSessionFailed = "Didit create session failed: {Status} {Body}";
    public const string LogGetSessionFailed = "Didit get session failed: {Status}";
    public const string LogWebhookReceived = "Didit webhook received: session={SessionId} status={Status}";
    public const string LogWebhookParseError = "Didit webhook payload parse error";
}
