namespace PrTask.Domain.Constants;
public static class FingerprintConstants
{
    public const string EndpointsFileName = "PrTask.Client.staticwebassets.endpoints.json";
    public const string HtmlExtension = ".html";
    public const string GzExtension = ".gz";
    public const string BrExtension = ".br";
    public const string WwwRootDir = "wwwroot";
    public const string IndexClean = "index";
    public const string LangIndexPattern = "^([a-z]{2,3})/index$";
    public const string RedirectStubTemplate = "<!DOCTYPE html><html><head><meta charset=\"utf-8\"/><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"/><title>{1}</title><meta name=\"description\" content=\"{2}\"/><meta http-equiv=\"refresh\" content=\"0;url={0}\"/><link rel=\"canonical\" href=\"{0}\"/><style>html,body{{margin:0;background:#1a1a2e}}</style></head><body><h1>{1}</h1></body></html>";
    public const string LogStartFormat = "Fingerprinting {0} HTML files in {1}";
    public const string LogEntryFormat = "  {0} -> {1}";
    public const string LogCompleteFormat = "Fingerprinting complete: {0} HTML files processed";
    public const string LogFoundFormat = "Found {0} fingerprinted HTML mappings";
    public const string HrefPattern = "href=\"";
    public const string SlashHrefPattern = "href=\"/";
    public const string DotSlashHrefPattern = "href=\"./";
    public const string AnchorHrefDotSlash = "(<a[^>]*?)href=\"\\./\"";
    public const string AnchorHrefSlash = "(<a[^>]*?)href=\"/\"";
    public const string PathSeparator = "/";
    public const string ParentDir = "../";
    public const string DoubleParentDir = "../../";
    public const string ParentHrefPattern = "href=\"../";
    public const string DoubleParentHrefPattern = "href=\"../../";
    public const string MetaRefreshParentUrl = "url=../";
    public const string MetaRefreshDoubleParentUrl = "url=../../";
    public const string AnchorHrefParentSlash = "(<a[^>]*?)href=\"\\.\\./\"";
    public const string AnchorHrefDoubleParentSlash = "(<a[^>]*?)href=\"\\.\\./(\\.\\./)\"";
    public const string BaseHrefTag = "    <base href=\"/\" />\n";
    public const string QuoteClose = "\"";
    public const string HashMark = "#";
    public const string EndpointsProperty = "Endpoints";
    public const string RouteProperty = "Route";
    public const string AssetFileProperty = "AssetFile";
    public const string DefaultPublishDir = "publish-output";
    public const string ErrorNotFound = "Endpoints file not found: ";
    public const string ErrorCleanNotFound = "  Clean file not found: ";
    public const string RegexGroupReplace = "$1";
    public const string MetaRefreshUrl = "url=";
    public const string MetaRefreshDotSlashUrl = "url=./";
    public const string MetaRefreshSlashUrl = "url=/";
    public const string RootIndexFile = "index.html";
    public const string EnIndexFile = "en/index.html";
    public const string NotFoundFile = "404.html";
    public const string CssExtension = ".css";
    public const string IcoExtension = ".ico";
    public const string PngExtension = ".png";
    public const string BrGlob = "*.br";
    public const string GzGlob = "*.gz";
    public const string HtmlGlob = "*.html";
    public const int FingerprintHashLength = 10;
    public const string LogLocaleFoundFormat = "Found {0} locale HTML files to fingerprint";
    public const string FingerprintDotFormat = "{0}.{1}.html";
    public const string FingerprintDotDirFormat = "{0}/{1}.{2}.html";
    public const string AlreadyFingerprintedPattern = @"\.[a-z0-9]{7,}\.(html|css|ico|png)$";
    public const string AlreadyFingerprintedFilePattern = @"\.[a-z0-9]{7,}\.";
}
