namespace PrTask.Domain.Constants;
public static class MauiConstants
{
    public const string RouteNotFound = "404 - Route not found";
    public const string SomethingWentWrong = "Something went wrong";
    public const string Reload = "Reload";
    public const string NotificationRunningText = "Running in background";
    public const string NotificationChannelDescription = "Keeps the app running for sync";
    public const int NotificationPermissionRequestCode = 100;
    public const string AndroidThemeNoActionBar = "@style/Maui.MainTheme.NoActionBar";
    public const string NotificationCloseAction = "com.prtask.app.CLOSE";
    public const string NotificationCloseText = "Close";
    public const string AuthCallbackScheme = "com.prtask.app://auth";
    public const string AuthSessionKey = "session";
    public const string AuthUsernameKey = "username";
    public const string AuthPlatformQuery = "?platform=android";
    public const string AuthPlatformParamName = "platform";
    public const string AuthPlatformAndroid = "android";
    public const string AuthPlatformCookie = "prtask_platform";
    public const string InvisibleLaunchExtra = "invisible_launch";
    public const string AndroidThemeTransparent = "@android:style/Theme.Translucent.NoTitleBar";
    public const int KestrelPollIntervalMs = 100;
    public const string NotificationChannelId = "prtask_server";
    public const int ServerNotificationId = 1;
    public const int CloseNotificationRequestCode = 2;
    public const int RestartNotificationRequestCode = 3;
    public const string NotificationServerPrefix = "Server: ";
    public const string NotificationServerTitle = "PrTask Server";
    public const string NotificationServerReady = "Tap to open in browser";
    public const string NotificationServerStarting = "Starting server...";
    public const string KestrelUrlExtra = "kestrel_url";
    public const string WifiIpFallback = "0.0.0.0";
    public const int WifiIpShift8 = 8;
    public const int WifiIpShift16 = 16;
    public const int WifiIpShift24 = 24;
    public const int WifiIpMask = 0xff;
    public const string IpAddressFormat = "{0}.{1}.{2}.{3}";
    public const int KestrelReadyPollMs = 250;
    public const string ContentTypeHtml = "text/html";
    public const string ContentTypeCss = "text/css";
    public const string ContentTypeJs = "application/javascript";
    public const string ContentTypePng = "image/png";
    public const string ContentTypeSvg = "image/svg+xml";
    public const string ContentTypeWasm = "application/wasm";
    public const string ContentTypeOctetStream = "application/octet-stream";
    public const string ExtensionCss = ".css";
    public const string ExtensionJs = ".js";
    public const string ExtensionJson = ".json";
    public const string ExtensionPng = ".png";
    public const string ExtensionSvg = ".svg";
    public const string ExtensionWasm = ".wasm";
    public const string ExtensionDat = ".dat";
    public const string HttpListenerPrefixFormat = "http://+:{0}/";
    public const string HttpServerUrlFormat = "http://0.0.0.0:{0}";
}
