using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using PrTask.Application.Services;
using PrTask.Client.Services;
using PrTask.Domain.Constants;
var Builder = WebAssemblyHostBuilder.CreateDefault(args);
Builder.RootComponents.Add<PrTask.Client.Components.ClientRoutes>(AppConstants.AppRootSelector);
Builder.Services.AddScoped(_ => new HttpClient { BaseAddress = new Uri(AppConstants.AppBaseUrl) });
Builder.Services.AddScoped<ILocalStoreService, LocalStoreService>();
Builder.Services.AddScoped<IConnectionStateService, WasmConnectionStateService>();
Builder.Services.AddScoped<IWssConnectionService, WasmWssConnectionService>();
Builder.Services.AddScoped<IWssService, WasmWssService>();
Builder.Services.AddScoped<IWebSocketReconnectionService, WasmWebSocketReconnectionService>();
Builder.Services.AddScoped<IVisibilitySyncService, WasmVisibilitySyncService>();
Builder.Services.AddScoped<IGitSyncService, NoOpGitSyncService>();
Builder.Services.AddScoped<ITaskService, WssTaskService>();
Builder.Services.AddScoped<IPullRequestService, WssPullRequestService>();
Builder.Services.AddScoped<IUserService, LocalUserService>();
Builder.Services.AddScoped<ILeaderboardService, WssLeaderboardService>();
Builder.Services.AddScoped<IPaymentRecordService, WssPaymentRecordService>();
Builder.Services.AddScoped<IBoardService, WssBoardService>();
Builder.Services.AddScoped<ISprintService, WssSprintService>();
Builder.Services.AddScoped<IRepositoryService, WssRepositoryService>();
Builder.Services.AddScoped<IReviewCommentService, WssReviewCommentService>();
Builder.Services.AddScoped<IInvoiceService, WssInvoiceService>();
Builder.Services.AddScoped<ISubscriptionService, WssSubscriptionService>();
Builder.Services.AddScoped<ISourceCodeService, WssSourceCodeService>();
Builder.Services.AddScoped<IVectorSearchService, WssVectorSearchService>();
Builder.Services.AddScoped<IKycVerificationService, WssKycVerificationService>();
Builder.Services.AddScoped<ICloudflareD1Service, WssCloudflareD1Service>();
Builder.Services.AddScoped<IInferenceService, WssInferenceService>();
Builder.Services.AddScoped<ISnapshotService, WssSnapshotService>();
await Builder.Build().RunAsync();
