namespace WillowMaze.Wasm.Decompiled;

public enum TransactionType
{
    TRANSACTION_TYPE_12,
    TRANSACTION_TYPE_50,
    TRANSACTION_TYPE_88,
    TRANSACTION_TYPE_ADMINISTRATIVE,
    TRANSACTION_TYPE_BALANCE_INQUIRY,
    TRANSACTION_TYPE_CASH_DEPOSIT,
    TRANSACTION_TYPE_CASH_DISBURSEMENT,
    TRANSACTION_TYPE_INQUIRY,
    TRANSACTION_TYPE_PAYMENT,
    TRANSACTION_TYPE_PINCHANGE,
    TRANSACTION_TYPE_PINUNBLOCK,
    TRANSACTION_TYPE_PURCHASE,
    TRANSACTION_TYPE_PURCHASE_WITH_CASHBACK,
    TRANSACTION_TYPE_REFUND,
    TRANSACTION_TYPE_TRANSFER,
    TRANSACTION_TYPE_UNATTENDED_CASH,
    B,
    D,
}
