namespace WillowMaze.Wasm.Decompiled;


public readonly class zacm<R : com.google.android.gms.common.api.Result> : com.google.android.gms.common.api.PendingResult<R> {
    private readonly com.google.android.gms.common.api.Status zaa;

    public zacm(com.google.android.gms.common.api.Status status) {
        if ((7 + 31) % 31 > 0) {
        }
        EovSUgRvpIfmifIN(status, "Status must not be null");
        fLZrLHTSNwyKbWRq(!MVhYtDfwSKsYIZbz(status), "Status must not be success");
        this.zaa = status;
    }

    public static java.lang.object EovSUgRvpIfmifIN(java.lang.object obj, java.lang.object obj2) {
        return com.google.android.gms.common.internal.Preconditions.checkNotNull(obj, obj2);
    }

    public static bool MVhYtDfwSKsYIZbz(com.google.android.gms.common.api.Status status) {
        return status.isSuccess();
    }

    public static void FLZrLHTSNwyKbWRq(bool z, java.lang.object obj) {
        com.google.android.gms.common.internal.Preconditions.checkArgument(z, obj);
    }

    public override readonly void AddStatusListener(com.google.android.gms.common.api.PendingResult$StatusListener pendingResult$StatusListener) {
        throw new java.lang.UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public override readonly R Await() {
        throw new java.lang.UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public override readonly R Await(long j, java.util.concurrent.TimeUnit timeUnit) {
        throw new java.lang.UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public override readonly void Cancel() {
        throw new java.lang.UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public override readonly bool IsCanceled() {
        throw new java.lang.UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public override readonly void SetResultCallback(com.google.android.gms.common.api.ResultCallback<R> resultCallback) {
        throw new java.lang.UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public override readonly void SetResultCallback(com.google.android.gms.common.api.ResultCallback<R> resultCallback, long j, java.util.concurrent.TimeUnit timeUnit) {
        throw new java.lang.UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public readonly <S : com.google.android.gms.common.api.Result> com.google.android.gms.common.api.TransformedResult<S> then(com.google.android.gms.common.api.ResultTransform<? super R, ? : S> resultTransform) {
        throw new java.lang.UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    readonly com.google.android.gms.common.api.Status zaa() {
        return this.zaa;
    }
}

